### ISSUE TITLE
Issues with install and launch

### ISSUE THREAD

**Issue by BlueInGreen68** [NikolaDucak/caps-log#54]
Hi. I encountered some difficulties during installation and startup `caps-log`:

1. During the build `cmake` could not find the path to the `OpenSSL`:

    ```bash
    CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
      system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY Crypto)
      (found version "3.3.0")
    ```

    I fixed it by changing one `set(OPENSSL_USE_STATIC_LIBS TRUE)` in the file `CmakeLists.txt` to:
    
    ```txt
    set(OPENSSL_USE_STATIC_LIBS OFF CACHE BOOL “” FORCE)
    ```

3. After a kinda successful installation, running `caps-log` doesn't output anything, but just blinks the cursor against an empty terminal background.

Can you please tell me what can be done?

**Comment by NikolaDucak-TomTom** [comment]
Hi, 
I've had similar issue before and i've fixed it by broviding the OPENSSL_ROOT_DIR to my cmake command `cmake .. -DOPENSSL_ROOT_DIR=/opt/homebrew/etc/openssl@3`. 

Can you try that?

**Comment by NikolaDucak** [comment]
Hi,
I've had similar issue before and i've fixed it by broviding the OPENSSL_ROOT_DIR to my cmake command cmake .. -DOPENSSL_ROOT_DIR=/opt/homebrew/etc/openssl@3.

Can you try that?

**Comment by NikolaDucak** [comment]
Sorry for the delayed response. 

Does `/usr/lib/openssl-1.1/` exist on your machine? 
Maybe you can try to set OPEN_SSL_ROOT_DIR to be just `/usr/lib`?

Also I see `/usr/lib/libcrypto.so` but no `*.a` so I guess you don't have a static library installed. Anyway of install openssl static lib with pacman? According to chat gpt is should be installed with openssl package `sudo pacman -S openssl
` which I assume you already did 

Sorry I'm not much of help here, I have no experience with arch & pacman. 

Also, perhaps this is not the real issue here, https://github.com/NikolaDucak/caps-log/issues/56 is an issue where caps log receives SIGABRT but does not close the app, just breaks the rendering.. perhaps similar thing is happening to you and that's why you get the blank screen, I'll look into that issue

**Comment by NikolaDucak** [comment]
@BlueInGreen68 a fix for #56 is on master, can you try running it again?

**Comment by BlueInGreen68** [comment]
@NikolaDucak I tried everything you mentioned above, but unfortunately none of it worked. I even tried changing the `set(OPENSSL_USE_STATIC_LIBS TRUE)` in `CmakeLists.txt` again to `set(OPENSSL_USE_STATIC_LIBS OFF CACHE BOOL “” FORCE)`, but after a “successful” installation I still get a dark screen, but I didn't specify the following message last time:

```bash
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (libgit2)
  does not match the name of the calling package (LibGit2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
```
Perhaps this message has something to do with the black screen, I apologize for my meager knowledge.

In searching for static libraries I came across a couple of packages but they take some unrealistic amount of time to install, however I did manage to install one package but it didn't help either.

But I am willing to try to implement your advice on my machine if any.

**Comment by NikolaDucak** [comment]
So this message is with the latest version of the master? 
Are you specifying any command line arguments and do you have anything set int your config? (~/.caps-log/config.ini)

**Comment by BlueInGreen68** [comment]
This message appeared after setting `set(OPENSSL_USE_STATIC_LIBS TRUE)` to `set(OPENSSL_USE_STATIC_LIBS OFF CACHE BOOL “” FORCE)`.

And running it with or without the config does not change anything. Still black screen. However, in the `~/.caps-log/` folder an empty `day` directory is created.

**Comment by BlueInGreen68** [comment]
Hi, your tool appeared in the AUR repository, but I'm encountering the same black screen error.
https://aur.archlinux.org/packages/caps-log-bin#comment-984570

**Comment by ByteCommander7** [comment]
@BlueInGreen68 ,

I've attempted to install this software on Arch Linux, and I am experiencing the same issues as you. Have you found a solution to successfully compile this software?

**Comment by NikolaDucak** [comment]
I haven't managed or seen this issue so far... Looks like it's only found on arch linux (so far)? 
Can anyone build it in debug and run it under a debugger then interrupt the process and post the stack trace?

**Comment by BlueInGreen68** [comment]
> I haven't managed or seen this issue so far... Looks like it's only found on arch linux (so far)? Can anyone build it in debug and run it under a debugger then interrupt the process and post the stack trace?

I can give it a try, will post the results shortly.

**Comment by ultracrepidarian7** [comment]
I'm also having the blank screen issue on Debian Sid. I've got like 20 other projects using ftxui running so I don't think it's a terminal thing, and I didn't see any complaints about SSL. Compiled with -DCMAKE_BUILD_TYPE=Debug and attached output, not sure if that exception is the cause of the problem or not. Let me know if that's normal and I'll probably keep poking at it.
[gdb.txt](https://github.com/user-attachments/files/17938904/gdb.txt)

**Comment by ultracrepidarian7** [comment]
Did a little digging, looks like dimx is 0 until the screen is drawn for the first time maybe?

```
  auto screen2 = ScreenInteractive::Fullscreen();
  cout << screen2.dimx() << endl;

  auto screen3 = ScreenInteractive::TerminalOutput();
  cout << screen3.dimx() << endl;
```

Prints 0, 0. So I tried the laziest fix I could think of at calendar_components line 62:

            if (columns == 0)
              columns = 1;
            if ((i + 1) % columns == 0) {
                renderData.push_back(hbox(currentHbox));
                currentHbox.clear();
            }

Looks like it's working now, with four columns. 

Very cool application btw, thanks for making it. I was trying to do something similar and got stuck trying to work with a functional gui, coming from an OOP background. Your code looks like it will help me learn.

**Comment by NikolaDucak** [comment]
Makes sense. Thanks for looking into this!
Looks like initial dimensions for ScreenInteractive::Fullscreen() are set to 0. I didn't find these values being overwritten later.
https://github.com/ArthurSonzogni/FTXUI/blob/dfa461b46b9098d566f73072827b9204315ffde2/src/ftxui/component/screen_interactive.cpp#L395

I did see that `Draw()` method of `ScreenInteractive` uses `Terminal::Size()` when it's in fullscreen mode. 
Can you try to build and run the app from `fix/empty-screen-on-startup` branch (PR #74)? If this works for you, I'll clean up the `Screen` usage in rendering and merge.

> Very cool application btw, thanks for making it. I was trying to do something similar and got stuck trying to work with a functional gui, coming from an OOP background. Your code looks like it will help me learn.

Than you, I'm glad you liked it! Although there might have been better approaches to structuring this code. I also come from OOP background and after trying out FTXUI i decided to wrap the UI code into classes to make it easier for myself, so keep in mind that you might not learn the best practices from this code 😅 

Thank you very much for finding the issues behind this!

**Comment by NikolaDucak** [comment]
> That did the trick, thanks for the fast fix!
Good, I cleaned things up and merged the fix!

> And thanks for the heads-up, that explains why the code makes so much sense to me 😄. I'm thinking of making something a little like taskwarrior with a TUI that looks similar to caps-log, to show every instance of a recurring task coming up and how much time you have blocked each day.

Sounds like an interesting tool, good luck! If you find a better way to create this type of UI, I might steal it from you 🙃

**Comment by BlueInGreen68** [comment]
> > I haven't managed or seen this issue so far... Looks like it's only found on arch linux (so far)? Can anyone build it in debug and run it under a debugger then interrupt the process and post the stack trace?
> 
> I can give it a try, will post the results shortly.

I apologize for the delay, it's great that you managed to solve the problem, for me the task was impossible 😄
